"""Build provenance (M27b tooling).

The install ran M26 while the repository was four milestones ahead, and
nothing in the running application could have told you so.
"""

from __future__ import annotations

import sys

import pytest

from qat import version
from qat.version import BuildInfo, build_info, stamp_module_source


def test_a_source_checkout_reports_the_live_commit():
    info = build_info()

    assert info.source == "source checkout"
    assert info.milestone == version.MILESTONE
    assert info.commit  # a real describe, or "unknown" off a checkout
    assert not info.is_packaged


def test_a_packaged_build_reads_its_stamp(monkeypatch, tmp_path):
    """The stamp is captured at package time because a frozen application has
    no git to ask afterwards."""
    module = type(sys)("qat._build_stamp")
    module.MILESTONE = "M99"
    module.COMMIT = "abc1234"
    module.BUILT_AT = "2026-07-30 22:17 UTC"
    monkeypatch.setitem(sys.modules, "qat._build_stamp", module)
    monkeypatch.setattr(version, "_frozen", lambda: True)

    info = build_info()

    assert info == BuildInfo(
        milestone="M99", commit="abc1234", built_at="2026-07-30 22:17 UTC", source="packaged"
    )
    assert info.is_packaged


def test_a_frozen_build_without_a_stamp_says_so(monkeypatch):
    """Rather than falling through to git, which inside a frozen app would
    report whatever checkout happens to sit beside the executable."""
    monkeypatch.setattr(version, "_frozen", lambda: True)
    monkeypatch.setattr(
        version, "_git", lambda *args: pytest.fail("a frozen build must not shell out to git")
    )

    info = build_info()

    assert info.source == "packaged, unstamped"
    assert info.commit == "unknown"


def test_git_failures_never_raise(monkeypatch):
    """No git on PATH, not a repository, a git that hangs - a version display
    is not worth failing startup for."""
    monkeypatch.setattr(version, "_frozen", lambda: False)
    monkeypatch.setattr(
        version, "_git", lambda *args: (_ for _ in ()).throw(OSError("git not found"))
    )

    with pytest.raises(OSError):
        version._git("describe")  # the stub itself raises, proving the patch is live

    monkeypatch.setattr(version, "_git", lambda *args: None)
    assert build_info().commit == "unknown"


def test_the_one_line_summary_carries_all_three_facts():
    info = BuildInfo(milestone="M27a", commit="db4a8e3", built_at="2026-07-30", source="packaged")

    line = info.one_line()

    assert "M27a" in line
    assert "db4a8e3" in line
    assert "2026-07-30" in line


def test_the_generated_stamp_is_importable_python():
    source = stamp_module_source("M27a", "db4a8e3-dirty", "2026-07-30 22:17 UTC")
    namespace: dict[str, object] = {}

    exec(compile(source, "_build_stamp.py", "exec"), namespace)  # nosec B102 - generated by us

    assert namespace["MILESTONE"] == "M27a"
    assert namespace["COMMIT"] == "db4a8e3-dirty"
    assert namespace["BUILT_AT"] == "2026-07-30 22:17 UTC"
